[build-system]
requires = ["jupyter_packaging~=0.10", "jupyterlab>=3.1.0rc1,==3.*"]
build-backend = "setuptools.build_meta"

[license]
file="LICENSE"

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"
