name: Release

on:
  # TODO: switch back to tag
  push:
    branches:
      - main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  release:
    # if: startsWith(github.ref, ‘refs/tags/’)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '12.x'
       registry-url: 'https://registry.npmjs.org'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine jupyter-packaging~=0.7.9 jupyterlab~=3.0
    - name: Build the package
      run: |
        # TODO: uncomment
        echo "build"
        # python setup.py sdist bdist_wheel
    # - name: Publish a Python distribution to PyPI
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        # TODO: uncomment
        echo "publish to npm"
        # jlpm run lerna publish from-package --yes
    - name: Get the current tag
      id: current_tag
      run: |
        tag=`git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1)`
        echo "::set-output name=tag::${tag}"
    - name: Get the previous tag
      id: previous_tag
      run: |
        tag=`git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1)`
        echo "::set-output name=tag::${tag}"
    - name: Generate Changelog
      env:
        CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
      run: |
        docker run --rm -v "$(pwd)":/usr/local/src/your-app \
          -e CHANGELOG_GITHUB_TOKEN=${CHANGELOG_GITHUB_TOKEN} \
          ferrarimarco/github-changelog-generator \
          github_changelog_generator -u jtpio -p jupyterlab-classic --usernames-as-github-logins --no-issues --no-unreleased \
          --since-tag ${{ steps.previous_tag.outputs.tag }} --header "" --pr-label "## Changes"
        head -n -1 CHANGELOG.md > CHANGELOG
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.current_tag.outputs.tag }}
        release_name: ${{ steps.current_tag.outputs.tag }}
        body_path: CHANGELOG
        # TODO: set to false?
        draft: true
        prerelease: false

