name: Release

on:
  # TODO: switch back to tag
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '12.x'
       registry-url: 'https://registry.npmjs.org'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine jupyter-packaging~=0.7.9 jupyterlab~=3.0
    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel
    # - name: Publish a Python distribution to PyPI
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        # TODO: uncomment
        echo "publish to npm"
        # jlpm run lerna publish from-package --yes
    - name: Generate Changelog
      env:
        CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
      run: |
        prev_tag=`git describe --abbrev=0 --tags "$(git rev-list --tags --skip=1 --max-count=1)"`
        docker run --rm -v "$(pwd)":/usr/local/src/your-app \
          -e CHANGELOG_GITHUB_TOKEN=${CHANGELOG_GITHUB_TOKEN} \
          ferrarimarco/github-changelog-generator \
          github_changelog_generator -u jtpio -p jupyterlab-classic usernames-as-github-logins --no-issues --no-unreleased \
          --since-tag ${prev_tag} --header "## Changes"
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: ${{ github.ref }}
    #     body_path: CHANGELOG.md
    #     # TODO: set to fals
    #     draft: true
    #     prerelease: false

